### ISSUE TITLE
Port on STM32F4 Error!

### ISSUE THREAD

**Issue by yetkieu846** [akospasztor/stm32-bootloader#2]
I have an STM32F4 Discovery board. And i am porting this code to my board. But it have so much error, mainly related to  HAL FLASH. I am using HAL library. Anyone have bootloader for STM32F4?

**Comment by akospasztor** [comment]
The STM32F4 disco is equipped with the STM32F407VG microcontroller. The F4xx microcontrollers (and their flash) differ a little bit from the L4xx MCU-s. Please refer to the F407 reference manual (RM0090, http://www.st.com/resource/en/reference_manual/dm00031020.pdf) and its datasheet to successfully port the application for the F4xx microcontrollers.
