### ISSUE TITLE
Support for STM32F4 series

### ISSUE THREAD

**Issue by ashishsk** [akospasztor/stm32-bootloader#54]
Hi, I am trying to adapt this library for STM32F401 MCU and it seems like there are a ton of configurations that are different. Could you suggest what's the best way to port this implementation to F4?

**Comment by akospasztor** [comment]
Hi Ashish,

It depends on what kind of hardware setup you have. Usually porting the bootloader-specific HAL commands from L4 family to F4 family should be pretty much straightforward if I remember correctly. The STM32 comes with tons of examples for F4 microcontrollers, and they are also available on GitHub (I'm not sure how up-t-date this is): https://github.com/STMicroelectronics/STM32CubeF4.

For instance, you can take a look at this example how to use the flash-related HAL commands on F401: https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Projects/STM32F401-Discovery/Examples/FLASH/FLASH_EraseProgram

If you also would like to port the SD-Card-related (or other) functionalities, then you need to dig a little bit deeper and understand what exactly are the differences between the peripherals of L4 and F4 microcontrollers. For this, I would recommend to check out the reference manual of the F401 (https://www.st.com/resource/en/reference_manual/rm0368-stm32f401xbc-and-stm32f401xde-advanced-armbased-32bit-mcus-stmicroelectronics.pdf). 

I hope this helps. 
Akos

**Comment by ashishsk** [comment]
Edit: removed inaccurate description 
Issue solved.
